In [1]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.11.0


In [2]:
# Creating tensors
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
vector.ndim

1

In [6]:
# Create a matrix
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix
new_matrix = tf.constant([[10., 7.], [3., 2.], [8., 9.]], dtype=tf.float16)
new_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
new_matrix.ndim

2

In [10]:
tensor = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [11]:
tensor.ndim

3

* Scalar: a single number (0-dim)
* Vector: a number with direction (1-dim)
* Matrix: a 2-dimensional array of numbers (2-dim)
* Tensors: an n-dimensional array of numbers (n-dim)

### Creating tensors with tf.Variable

In [12]:
# Create the same tensor with tf.Variable as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [14]:
# Change an element of tensor variable
changeable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [15]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [17]:
# Changing unchangeable tensor
unchangeable_tensor[0] = 7

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [18]:
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Creating Random Tensors

Tensors of some arbitrary size which contains random numbers.

In [27]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffling tensors elements

In [52]:
# Shuffle a tensor (when you want to shuffle in a way that won't affect the results)
not_shuffled = tf.constant([[10, 7], [3, 4], [2, 5]])
not_shuffled.ndim, not_shuffled

(2,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  5]])>)

In [65]:
# Shuffles only along the first dimension
# Operation level seed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [70]:
# Global level seed
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

### Numpy arrays to tensors

Tensors can be run on a GPU at much faster speeds.

In [71]:
tf.ones((3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [72]:
tf.zeros((3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [17]:
import numpy as np

In [76]:
numpy_A = np.arange(1, 25, dtype=np.int16)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [79]:
2 * 3 * 4

24

In [78]:
tensor_A = tf.constant(numpy_A, shape=(2, 3, 4))
tensor_B = tf.constant(numpy_A)
tensor_A, tensor_B

<tf.Tensor: shape=(2, 3, 4), dtype=int16, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int16)>

### Getting information from tensors

In [3]:
rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [13]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [14]:
# Get various attributes
print(f'Datatype of every element: {rank_4_tensor.dtype}')
print(f'Number of dimensions (rank): {rank_4_tensor.ndim}')
print(f'Shape of tensor: {rank_4_tensor.shape}')
print(f'Elements along the zero axis: {rank_4_tensor[0].shape[0]}')
print(f'Elements along the last axis: {rank_4_tensor.shape[-1]}')
print(f'Total number of element in our tensor: {tf.size(rank_4_tensor)}')

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the zero axis: 3
Elements along the last axis: 5
Total number of element in our tensor: 120


### Indexing tensors

Same indexing as in python lists and numpy

In [ ]:
# Get the first 2 elements of each dimension

In [4]:
rank_4_tensor[2:,2:,2:,2:]

<tf.Tensor: shape=(0, 1, 2, 3), dtype=float32, numpy=array([], shape=(0, 1, 2, 3), dtype=float32)>

In [8]:
# Get the first element from each dimension from each index except the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [10]:
# Create a rank 2 tensor
rank_2_tensor = tf.constant([[10, 7], [3, 4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [13]:
# Get the last item of each row
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [14]:
# Add an extra dimension
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [15]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # -1 expand the last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [18]:
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]])>

### Manipulating tensors (tensor operations)

**Basic operations**

`+`, `-`, `*`, `/`

In [20]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [21]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [22]:
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [23]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

**We can use the tf built-in function too**

Usually faster

In [28]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [25]:
tf.math.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

**Matrix multiplication**

In ML, one of the most common operations.

Everything before this were element-wise operations

1. The inner dimension must match
2. The resulting matrix has the shape of the inner dimension

Consider these dimensions (a, b) and (c, d). Then, to multiply, b = c.

In [29]:
# tf.matmul()
tf.linalg.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [30]:
tensor, tensor * tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  49],
        [  9,  16]])>)

In [32]:
# Matrix multiplication with Python using `@` operator
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [38]:
A = tf.constant([[1, 2, 5], [7, 2, 1], [3, 3, 3]])
B = tf.constant([[3, 5], [6, 7], [1, 8]])
tf.matmul(A, B)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

In [39]:
B, tf.transpose(B)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 6, 1],
        [5, 7, 8]])>)

In [40]:
tf.reshape(B, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 6],
       [7, 1, 8]])>

**The dot product**

Matrix multiplication is the same as dot product

* `tf.matmul()`
* `tf.tensor_dot()`

In [42]:
A, B

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]])>)

In [45]:
tf.matmul(A, B)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

In [44]:
# Perform the dot product on A and B
tf.tensordot(A, B, axes=1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

### Changing the datatype of a tensor

In [49]:
# Create a new tensor with default datatype (tf.float32) [depending on the given data]
A = tf.constant([1, 4])
B = tf.constant([1.7, 7.4])
A, B

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4])>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>)

There are two lower precision datatypes than `float32`. `float16`, `bfloat16`. Lowering precision can speed up the computations.

In [52]:
B = tf.cast(B, dtype=tf.float16)
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

**Aggregating tensors**

Aggregating tensors = condensing them from multiple values to a smaller amount of values

In my own words, _truncating data_.

In [2]:
# Getting the absolute value (not an aggregation)
X = tf.constant([-7, -10])
tf.abs(X)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

* Minimum
* Maximum
* Mean
* Sum
* Product
* Standard deviation

In [5]:
# Creating a random tensor
X = tf.constant(np.random.randint(0, 100, size=50))
X

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([65, 82, 59, 58, 72, 52, 21, 39, 44, 25, 53, 13, 21, 40, 36, 60, 80,
       28, 52, 43, 26, 60, 79, 83, 47,  8, 83, 47, 10,  4, 92, 73, 56, 79,
       95, 17,  2, 95,  6, 36, 78, 75, 80, 83,  3, 71, 68, 31, 76, 35])>

In [6]:
# Find the minimum
tf.reduce_min(X)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [7]:
# Find the max
tf.reduce_max(X)

<tf.Tensor: shape=(), dtype=int32, numpy=95>

In [8]:
# Find the mean
tf.reduce_mean(X)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [9]:
# Find the sum
tf.reduce_sum(X)

<tf.Tensor: shape=(), dtype=int32, numpy=2541>

In [10]:
# Find the product
tf.reduce_prod(X)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [13]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(X, tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=27.25>

**Find the positional maximum and minimum**

In [14]:
# Create a new tensor for finding positional minimum and maximum
X = tf.constant(np.random.uniform(0, 100, size=50))
X

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([29.70798632, 71.99746867, 17.1006553 , 68.07162298, 26.68842952,
        5.93385882, 62.4138928 , 60.18766296, 37.96107805, 36.76232222,
       17.92421976, 37.29398963, 73.49809917, 82.20214671, 29.07644937,
       61.72746747,  3.57706939, 26.63471893, 95.37478957, 10.96363932,
       27.7263394 , 23.77953657, 37.19307063,  0.62355238, 42.45509024,
       76.6700286 , 33.16836739, 54.37702797, 98.75323243, 78.37608771,
       62.70113659,  0.88661805, 74.86725788, 46.45256006, 97.21024334,
       72.73270364, 85.00988991, 67.02932709, 84.10949585, 44.32797047,
       95.38415553, 71.34249852, 25.29066899, 87.40790754, 51.46245485,
       91.06152764, 71.07890569, 44.77988527, 75.87464257, 81.44767375])>

In [15]:
# Find the positional maximum
tf.argmax(X)

<tf.Tensor: shape=(), dtype=int64, numpy=28>

In [19]:
# Index on largest value
X[tf.argmax(X)], X[tf.argmax(X)] == tf.reduce_max(X)

(<tf.Tensor: shape=(), dtype=float64, numpy=98.75323243300531>,
 <tf.Tensor: shape=(), dtype=bool, numpy=True>)

In [20]:
# Find the positional minimum
tf.argmin(X)

<tf.Tensor: shape=(), dtype=int64, numpy=23>

In [21]:
# Index on smallest value
X[tf.argmin(X)]

<tf.Tensor: shape=(), dtype=float64, numpy=0.6235523819693056>

### Squeezing a tensor (removing all single dimensions)

Removes all the dimensions that have size one.

In [23]:
# Create a tensor
X = tf.constant(tf.random.uniform(shape=(50,)), shape=(1, 1, 1, 1, 50))
X

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.16012943, 0.9429884 , 0.22587907, 0.51447916, 0.6617484 ,
           0.8689053 , 0.51493   , 0.3722787 , 0.32548904, 0.33004224,
           0.3081298 , 0.06205463, 0.88686335, 0.87487257, 0.69593143,
           0.8860475 , 0.01403201, 0.322322  , 0.6462914 , 0.34346437,
           0.65689373, 0.319919  , 0.66745603, 0.40083504, 0.6945983 ,
           0.921232  , 0.9449848 , 0.5977646 , 0.37373674, 0.9667603 ,
           0.5955547 , 0.11796319, 0.71895504, 0.27747738, 0.23087001,
           0.4765098 , 0.9034326 , 0.885195  , 0.18621302, 0.8001754 ,
           0.32412493, 0.88139343, 0.11939788, 0.4412434 , 0.26902092,
           0.9601587 , 0.8503907 , 0.98562694, 0.91185176, 0.3549682 ]]]]],
      dtype=float32)>

In [24]:
X.shape

TensorShape([1, 1, 1, 1, 50])

In [25]:
X_squeezed = tf.squeeze(X)
X_squeezed, X_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.16012943, 0.9429884 , 0.22587907, 0.51447916, 0.6617484 ,
        0.8689053 , 0.51493   , 0.3722787 , 0.32548904, 0.33004224,
        0.3081298 , 0.06205463, 0.88686335, 0.87487257, 0.69593143,
        0.8860475 , 0.01403201, 0.322322  , 0.6462914 , 0.34346437,
        0.65689373, 0.319919  , 0.66745603, 0.40083504, 0.6945983 ,
        0.921232  , 0.9449848 , 0.5977646 , 0.37373674, 0.9667603 ,
        0.5955547 , 0.11796319, 0.71895504, 0.27747738, 0.23087001,
        0.4765098 , 0.9034326 , 0.885195  , 0.18621302, 0.8001754 ,
        0.32412493, 0.88139343, 0.11939788, 0.4412434 , 0.26902092,
        0.9601587 , 0.8503907 , 0.98562694, 0.91185176, 0.3549682 ],
       dtype=float32)>,
 TensorShape([50]))

### One-Hot Encoding

In [27]:
# Create a list of indices
color_list = [0, 1, 2, 3] # Could be red, green, blue, purple

In [28]:
# One-hot encode the color list
tf.one_hot(color_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

The elements in the list represent the identity base matrix of the colors

In [29]:
# Specify custom values for one hot encoding
tf.one_hot(color_list, depth=4, on_value='hello', off_value='byeee')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'hello', b'byeee', b'byeee', b'byeee'],
       [b'byeee', b'hello', b'byeee', b'byeee'],
       [b'byeee', b'byeee', b'hello', b'byeee'],
       [b'byeee', b'byeee', b'byeee', b'hello']], dtype=object)>

In [30]:
color_list = [2, 1, 0, 3] # Could be red, green, blue, purple
tf.one_hot(color_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [31]:
tf.one_hot(color_list, depth=3)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [32]:
tf.one_hot(color_list, depth=6)

<tf.Tensor: shape=(4, 6), dtype=float32, numpy=
array([[0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]], dtype=float32)>

### Squaring, log, square root

In [33]:
X = tf.range(1, 10)
X

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [34]:
X ** 2

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [35]:
tf.square(X)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [36]:
tf.sqrt(X)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt]

In [37]:
tf.sqrt(tf.cast(X, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [38]:
tf.math.log(tf.cast(X, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

### Tensors and NumPy

In [39]:
# Create a tensor directly from a NumPy array
X = tf.constant(np.array([3., 7., 10,]))
X

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [44]:
np.array(X), X.numpy()

(array([ 3.,  7., 10.]), array([ 3.,  7., 10.]))

In [46]:
# The default types of each are slightly different
tf.constant(np.array([3., 7., 10])).dtype, tf.constant([3., 7., 10.]).dtype

(tf.float64, tf.float32)

NumPy array -> Tensor - float64
Python array -> Tensor - float32

### Finding access to GPUs

In [48]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]